# Site
name: "CoopGroup Robotics"
title: "CoopGroup"
description: "CoopGroup is a free coding club based in ATX. For kids, by kids."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
mailchimp-list: 'dced7714debf2e05cca0e3abb&id=165be60432'
include: ["_pages"]
permalink: /:title/

# Social media networks
github: CoopGroupATX
twitter: coop_group
discord: ZGxA46u

# Support Us
patreon: coopgroup
teespring: coopgroup-2

# Authors
authors:
  - name: Cooper Smallwood
    avatar: 'assets/images/cooper.jpg'
    role: Founder
    youtube: UCQ_jWBRns1bQWy0VH_zmrlA
    github: CooperSma
    email: cooper.smallwood0@gmail.com
    description: Hi my name is Cooper. Ever since I was three, I loved coding and robotics. One day, I had an idea to create a robotics club and this is the result.
  
  - name: Reese Armstrong
    avatar: 'assets/images/reese.jpg'
    role: Chief Instructor
    description: I'm Reese Armstrong an instructor here who loves helping people with technology, *NIX, and other technologies. I even helped make this website! 
    youtube: UCzXRd1MPx__6JjHAeP_9AIA
    github: reesericci

# Dates
dates:
  - image: https://lh3.googleusercontent.com/_4zBNFjA8S9yjNB_ONwqBvxTvyXYdC7Nh1jYZ2x6YEcldBr2fyijdjM2J5EoVdTpnkA
    alt: Customizing Discord
    title: Customizing Discord
    info: We used Bandaged-BD to build custom themes and plugins for discord.
    completed: true
  
  - image: https://images.unsplash.com/photo-1542831371-29b0f74f9713?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=2000&fit=max&ixid=eyJhcHBfaWQiOjExNzczfQ
    alt: Web-Design
    title: Web-Developer
    info: We learned html,css and js, the basics of web-development.
    completed: true
    
  - image: https://www.autoauto.ai/wp/wp-content/uploads/2020/05/4386785.jpg
    alt: Self Driving Minuture Car Programming
    title:  Self Driving Minuture Car Programming
    info: Students use Auto-Auto AI cars to learn python.
    completed: true
  
  - image: https://cdn.instructables.com/FOF/WVU6/JN3HXMRV/FOFWVU6JN3HXMRV.LARGE.jpg?auto=webp&frame=1&width=700&fit=bounds
    alt: Otto Photo
    title: Otto Coding
    info: Programing 3D printed robots (complete). 
    completed: true
  
  
# Navigation
nav:
- name: Home
  link: /
- name: Support Us
  link: /support-us
- name: About
  link: /about
- name: Sign Up
  link: /sign-up
- name: Dates
  link: /dates

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true




# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
